### ISSUE TITLE
Excavator server uses 100% CPU

### ISSUE THREAD

**Issue by Enterprize-1701** [nicehash/excavator#63]
Hello! I Updated recently NiceHash Miner to v 2.0.1.4 beta and after that Excavator server start using 100% of the CPU, but in settings I set up not to mine on CPU.
In previous versions of the miner excavator used maximum 40% of the CPU.

**Comment by Enterprize-1701** [comment]
The issue is gone after I reinstall vc_redist_2015_x64.exe.
maybe you have to check the miner Installer.

**Comment by dropky** [comment]
We are aware of this issue. It's not related to Excavator, but NiceHash Miner. If you run standalone excavator is the CPU load still at 50-60%?

**Comment by cmelion** [comment]
I'm seeing this too, CPU starts out ~15% but overnight it can reach 60-80% (GPU only mining).

**Comment by dropky** [comment]
@cmelion Are you using NiceHash Miner or standalone excavator?

**Comment by cmelion** [comment]
@dropky Nicehash Miner v 2.0.1.4 beta (latest).
```
Running on Windows 10.
Old AMD Phenom II 4 core.
3 Gigabyte GTX 750TI Windforce OC 4GB cards.
```

**Comment by dropky** [comment]
@cmelion Thanks for the information. We're looking into this.

**Comment by dropky** [comment]
We released a new version today that's addressing this issue. 

https://github.com/nicehash/excavator/releases/tag/v1.3.7a

If the CPU usage is still high, please let me know.

**Comment by cmelion** [comment]
@dropky I'm running the update.
So far so good.  Will let you know if there are any issues.

**Comment by ilgrank** [comment]
Nicehash 2.0.1.11: Issue appeared again.
GPU only mining, starts at 10% gpu usage, gets to 100% after a few hours.
Closing and restarting, and the same happens (starts low, gets to 100%)

**Comment by abhishekminer** [comment]
I am also facing this issue cpu usage 100%
Windows 10 64-bit
I3 6600 3.7Ghz 
4gb ram
Nvidia 1080ti inno3d 11gb no.  Of cards 12 
256GB ssd 
Vurtual memory set at 140 gb

Using nicehas latest version still issue not resolved plz help
